//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkySchool
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SkySchoolEntities : DbContext
    {
        public SkySchoolEntities()
            : base("name=SkySchoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Disciplina> Disciplina { get; set; }
        public virtual DbSet<Gruppa> Gruppa { get; set; }
        public virtual DbSet<Ocenka_Po_Predmetu> Ocenka_Po_Predmetu { get; set; }
        public virtual DbSet<SpisokDisciplin> SpisokDisciplin { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tip_Zanyatiya> Tip_Zanyatiya { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
