//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkySchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocenka_Po_Predmetu
    {
        public int ID_Ocenka { get; set; }
        public int ID_Disciplina { get; set; }
        public int ID_Tip_Zanyatiya { get; set; }
        public int ID_Student { get; set; }
        public int Ocenka { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Disciplina Disciplina { get; set; }
        public virtual Student Student { get; set; }
        public virtual Tip_Zanyatiya Tip_Zanyatiya { get; set; }
    }
}
