//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkySchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpisokDisciplin
    {
        public int ID_SpisokDisciplin { get; set; }
        public int ID_User { get; set; }
        public int ID_Disciplina { get; set; }
        public int ID_Tip_Zanyatiya { get; set; }
    
        public virtual Disciplina Disciplina { get; set; }
        public virtual Tip_Zanyatiya Tip_Zanyatiya { get; set; }
        public virtual User User { get; set; }
    }
}
